### ISSUE TITLE
Etcd storage class doesn't work in Minikube (only aws/gcp)

### ISSUE THREAD

**Issue by philwinder** [pachyderm/helmchart#10]
Hi there. This todo: https://github.com/pachyderm/helmchart/blob/master/pachyderm/templates/etcd/statefulset.yaml#L63

Prevents etcd starting on Minikube. It expects the storage class to exist and when it doesn't the PVC can't bind.

I propose that it should default to the default storage class, or allow the user to set/override in the values.yaml.

Thanks!

**Comment by chainlink** [comment]
Thanks for reporting! We're currently working through each deploy target (AWS, GCP, local, etc) and will flag to address when we validate the local case.

**Comment by chainlink** [comment]
Done!
