### ISSUE TITLE
Init checks for pachd 

### ISSUE THREAD

**Issue by chainlink** [pachyderm/helmchart#27]
Check if etcd (and postgres in 2.0) are running before booting pachd pod

**Comment by chainlink** [comment]
cc @seslattery

**Comment by seslattery** [comment]
I think we should include pachd's dependencies in the liveliness probe, though defining a separate startupProbe is probably also a good idea too (though that limits us to k8s 1.16 - I'm not sure what our Kubernetes version support story is)
