### ISSUE TITLE
Issue with prometheus port name: "must be no more than 15 characters"

### ISSUE THREAD

**Issue by philwinder** [pachyderm/helmchart#41]
Hey Kyle!

Quick issue. The name for the prom port is invalid. Annoyingly it doesn't validate properly on the local side, and passes. But when you apply it (I'm on 1.20 Minikube atm) it fails.

> Error: Service "pachd" is invalid: spec.ports[8].targetPort: Invalid value: "prometheus-metrics": must be no more than 15 characters

https://github.com/pachyderm/helmchart/blob/master/pachyderm/templates/pachd/service.yaml#L67

Renaming to prom-metrics should fix. Will create a PR.

**Comment by robert-uhl** [comment]
Also fixed in #40, which renames the `targetPort` to ‘prometheus’ (and does a whole heck of a lot more!). Any strong opinion either way? I think it’s just an internal reference, so as long as it’s readable it works.

**Comment by chainlink** [comment]
Going to merge for now to unblock Phil, happy to iterate on naming if needed though
