### ISSUE TITLE
Move 'LoadBalancer' section under pachd, rename to 'externalService' and make ports configurable

### ISSUE THREAD

**Issue by chainlink** [pachyderm/helmchart#65]
- Move the load balancer section under pachd in `values.yaml` as it only controls pachd
- Rename to `externalService` instead of loadbalancer for consistency (controls a `service` object)
- Make external port numbers configurable for this service - Folks might want to be able to access pachd on a custom external port

**Comment by philwinder** [comment]
Hi @chainlink . Just stumbled across this. My use case: I need to use nodeports for a demo, but the pach dash defaults to 30081, and there is no setting to change this. 

My browser inspector suggests that it is configurable:

```
var port = this.paramsFor('application').port;
```

We just need to pass this in at the chart level.

**Comment by chainlink** [comment]
@philwinder just circling back here, I have a PR which makes the pach ports configurable, but Dash is typically accessed behind an ingress. Does that work for your use case?
