### ISSUE TITLE
TLS configuration Changes [ High prio, blocks chart installation ]

### ISSUE THREAD

**Issue by chainlink** [pachyderm/helmchart#77]
Right now, we half enable TLS by default by specifying a secret name and hoping the user specifies the cert. Default should be either A) fully disabled or B) Enabled, but with an error message for cert

As well, specifying no TLS is a bit awkward

```
tls:
  certName: "" // Must be empty string
  create: null // must be null
```

We should change this to be more straightforward

cc @robert-uhl

**Comment by robert-uhl** [comment]
Agreed, it is awkward and should be better.

I think the cases we have to support are:

 1. Creating a specific key/cert/secret: ‘Here is a key; here is the certificate; here is the name of a secret to create and store them in (and retrieve them from).’
 2. Using an existing secret: ‘Here is the name of a pre-existing secret to retrieve the certificate and key from.’
 3. No TLS at all.

Maybe these should be the values:

```yaml
tls:
  secret:
    cert: ""
    key: ""
    name: ""
```

Then the three cases would be indicated by:

 1. Creating a specific key/cert/secret: `tls.secret.cert`, `tls.secret.key` & `tls.secret.name` all have values.
 2. Using an existing secret: `tls.secret.name` has a value, but the other two are blank.
 3. No TLS at all: all three values are empty, or `tls.secret` itself is empty.

What do you think? It’s an incompatible change, but … we are still in beta.

**Comment by robert-uhl** [comment]
Or just:

```yaml
tls:
  cert: ""
  key: ""
  name: ""
```
