### ISSUE TITLE
IAM Roles for EKS Pods

### ISSUE THREAD

**Issue by eytanhanig** [pachyderm/helmchart#88]
This chart currently supports IAM roles for GKE but **not** [IAM roles for pods on EKS](https://docs.aws.amazon.com/eks/latest/userguide/iam-roles-for-service-accounts.html). This is blocking my company's adoption.

Here are two easy methods to add this functionality:
1. Add Helm values for specifying the IAM role name for the two service accounts, which is [as simple as adding the annotation](https://docs.aws.amazon.com/eks/latest/userguide/specify-service-account-role.html) `eks.amazonaws.com/role-arn: ...`
1. A more universal solution solution is to allow users to specify additional annotations for each of the two service accounts. There are examples of this in a plethora of other popular helm charts.

**Comment by chainlink** [comment]
Heya @eytanhanig! Thanks for the suggestions. Happy to add the `additionalAnnotations` section. I should have a PR up in the next day or two.

**Comment by chainlink** [comment]
Now published as chart version 0.6.1 🚀
