### ISSUE TITLE
Node Affinity

### ISSUE THREAD

**Issue by eytanhanig** [pachyderm/helmchart#90]
For shared clusters it's essential that Pachyderm not compete for resources with other production applications. [There are a number of methods for doing](https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/), all of which require additions to the Pod's spec. This is currently impossible to do with this Helm chart.

**Please make it possible to restrict Pachyderm to specific nodes** as per [this official documentation](https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/). The quickest implementation of this would be to allow users to specify additional yaml that should be added to the spec.

**Comment by chainlink** [comment]
I have a draft PR here, will ship next week
